services:
  app:
    container_name: projectkit-dev
    image: projectkit/ui-dev
    build:
      context: ..
      dockerfile: .devcontainer/Dockerfile
      args:
        VARIANT: 3.13-bookworm
    volumes:
      - ../..:/workspaces:rw,cached
    command: sleep infinity
    networks:
      - projectkit-network

  db:
    container_name: projectkit-db
    image: pgvector/pgvector:pg15
    restart: unless-stopped
    volumes:
      - postgres-data:/var/lib/postgresql/data
    environment:
      POSTGRES_USER: postgres
      POSTGRES_DB: projectkit-db
      POSTGRES_PASSWORD: postgres
    ports:
      - 5433:5432
    networks:
      - projectkit-network

volumes:
  postgres-data:
    name: projectkit-postgres-data
networks:
  projectkit-network:
    driver: bridge
